Repository ecanquiz/node-auto-crudx, pull requests merged in 2023-04, with the labels that each got.

#1 wip: Creating model DB
  app.ts
  config/db.ts
  docs/queries.sql
  modules/db.ts
  modules/loadData.ts
Labels: enhancement

#2 feat: Creating DB & GetData
  app.ts
  docs/queries.sql
  modules/DB.ts
  modules/GetData.ts
  modules/db.ts
  modules/loadData.ts
Labels: enhancement

#3 feat: uCamelCase & camelCase utils
  app.ts
  docs/doc
  utils/nomenclature.ts
Labels: enhancement

#5 Develop
  .gitignore
  app.ts
  docs/content.example
  modules/GetData.ts
  modules/db.ts
  modules/renderings/demo.ts
  modules/renderings/vue/datagrid.ts
  processes/codeStandard.ts
  processes/getDataOfBD.ts
  processes/rendering.ts
  templates/vue/views/index
  utils/consoleLog.ts
Labels: enhancement

#6 feat: Iterate fiels rendering for each
  app.ts
  modules/renderings/vue/datagrid.ts
  processes/codeStandard.ts
  processes/getDataOfBD.ts
  processes/rendering.ts
  processes/writeFrontend.ts
  templates/vue/views/index
  types/index.ts
  utils/excludeFiles.ts
  utils/grammaticalNumber.ts
  utils/plural.ts
Labels: enhancement

#8 fix: tableDetailForeignKeysAssoc & tableForeignKeysAssocMasterDetail
  app.ts
  modules/db.ts
  processes/getDataOfBD.ts
  templates/vue/views/index
  types/index.ts
Labels: enhancement

#9 feat: createOrEditMaster & tabs
  app.ts
  modules/renderings/vue/createOrEditMaster.ts
  modules/renderings/vue/tabs.ts
  processes/writeFrontend.ts
  templates/vue/views/createOrEditMaster
  templates/vue/views/index
  templates/vue/views/tabs
Labels: enhancement

#11 refactor: Boilerplate code
  app.ts
  modules/renderings/vue/createOrEditMaster.ts
  modules/renderings/vue/datagrid.ts
  modules/renderings/vue/index.ts
  modules/renderings/vue/tabs.ts
  processes/getDataOfBD.ts
  processes/writeFrontend.ts
  templates/vue/views/tabs
  types/index.ts
  types/utilsRendering.ts
  utils/rendering.ts
Labels: duplicate, enhancement

#13 docs: README
  README.md
Labels: documentation, enhancement

#15 feat: Allow adding relative path aliases
  package-lock.json
  package.json
  src/app.ts
  src/customTypes/index.ts
  src/customTypes/utilsRendering.ts
  src/modules/db.ts
  src/modules/renderings/vue/createOrEditMaster.ts
  src/modules/renderings/vue/datagrid.ts
  src/modules/renderings/vue/tabs.ts
  src/processes/getDataOfBD.ts
  src/processes/writeFrontend.ts
  src/utils/rendering.ts
  tsconfig.json
Labels: enhancement

#17 feat: Output the app folder outside project directory
  .env.example
  .gitignore
  src/config/output.ts
  src/utils/rendering.ts
Labels: enhancement

#23 feat: Create the first test file in the backend
  .env.example
  src/app.ts
  src/config/output.ts
  src/customTypes/db.ts
  src/modules/renderings/laravel/controller.ts
  src/modules/renderings/laravel/index.ts
  src/modules/renderings/vue/tabs.ts
  src/processes/getDataOfBD.ts
  src/processes/writeBackend.ts
  src/processes/writeFrontend.ts
  src/templates/laravel/controller
Labels: enhancement

#24 feat: Recursive function that validates if the folder or file exists
  src/modules/renderings/laravel/controller.ts
  src/modules/renderings/vue/createOrEditMaster.ts
  src/modules/renderings/vue/datagrid.ts
  src/modules/renderings/vue/tabs.ts
  src/utils/createOutputPath.ts
  src/utils/rendering.ts
Labels: enhancement
